name: 'code-quality'
on:
  workflow_call:
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
      - name: 'Setup Bun'
        uses: ./.github/actions/setup-bun
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Perform typescript type checking'
        run: bun run turbo:typecheck
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
      - name: 'Setup Bun'
        uses: ./.github/actions/setup-bun
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Lint sources'
        run: bun run turbo:lint
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        options: >- # postgres container does not provide a health check
          --health-cmd pg_isready
          --health-interval 1s
          --health-timeout 1s
          --health-retries 30
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:4-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: ci
          RABBITMQ_DEFAULT_PASS: ci
          RABBITMQ_DEFAULT_VHOST: ci
        ports:
          - "5672:5672"
          - "15672:15672"
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
      - name: 'Setup Bun'
        uses: ./.github/actions/setup-bun
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Run all tests'
        env:
          NODE_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USERNAME: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DATABASE: ci
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_VHOST: ci
          RABBITMQ_USERNAME: ci
          RABBITMQ_PASSWORD: ci
        run: bun run turbo:test
